# Generated by Django 5.0.6 on 2024-07-06 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_fabric"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Textile",
        ),
    ]
